#!/usr/bin/env sh
#
set -eu

cd /usr/local/AppCentral/cappysan-jellyfin
if test -f CONTROL/start-stop.sh; then
  cp /usr/builtin/etc/certificate/ssl.p12 .
  chown jellyfin:0 ssl.p12
  chmod 600 ssl.p12

  ./CONTROL/start-stop.sh restart
fi
