---
# ------------------------------------------------------------------------------
# Global workflow
# ------------------------------------------------------------------------------
# https://docs.gitlab.com/ee/ci/yaml/workflow.html#switch-between-branch-pipelines-and-merge-request-pipelines
#
variables:
  PIPELINE_NAME: 'Unnamed pipeline'

workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"'
      when: never

    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always
      variables:
        ALLOW_FAILURE: "true"
        PIPELINE_NAME: "Merge request pipeline (#$CI_MERGE_REQUEST_ID - $CI_COMMIT_SHORT_SHA)"

    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never

    - if: '$CI_COMMIT_TAG'
      when: always
      variables:
        ALLOW_FAILURE: "true"
        PIPELINE_NAME: "Tag pipeline ($CI_COMMIT_TAG - $CI_COMMIT_SHORT_SHA)"

    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always
      variables:
        PIPELINE_NAME: "Scheduled pipeline ($CI_COMMIT_BRANCH)"

    - when: always
      variables:
        ALLOW_FAILURE: "false"
        PIPELINE_NAME: "Branch pipeline ($CI_COMMIT_BRANCH - $CI_COMMIT_SHORT_SHA)"
